// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/game/v1/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float64               `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y             *float64               `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_chat_game_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_chat_game_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_chat_game_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *Move) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Move) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_chat_game_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_game_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_chat_game_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *Chat) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_chat_game_v1_client_proto protoreflect.FileDescriptor

const file_chat_game_v1_client_proto_rawDesc = "" +
	"\n" +
	"\x19chat/game/v1/client.proto\x12\fchat.game.v1\"\"\n" +
	"\x04Move\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\" \n" +
	"\x04Chat\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageBz\n" +
	"\x10com.chat.game.v1B\vClientProtoP\x01Z\a./proto\xa2\x02\x03CGX\xaa\x02\fChat.Game.V1\xca\x02\fChat\\Game\\V1\xe2\x02\x18Chat\\Game\\V1\\GPBMetadata\xea\x02\x0eChat::Game::V1b\beditionsp\xe8\a"

var (
	file_chat_game_v1_client_proto_rawDescOnce sync.Once
	file_chat_game_v1_client_proto_rawDescData []byte
)

func file_chat_game_v1_client_proto_rawDescGZIP() []byte {
	file_chat_game_v1_client_proto_rawDescOnce.Do(func() {
		file_chat_game_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_game_v1_client_proto_rawDesc), len(file_chat_game_v1_client_proto_rawDesc)))
	})
	return file_chat_game_v1_client_proto_rawDescData
}

var file_chat_game_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_game_v1_client_proto_goTypes = []any{
	(*Move)(nil), // 0: chat.game.v1.Move
	(*Chat)(nil), // 1: chat.game.v1.Chat
}
var file_chat_game_v1_client_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_game_v1_client_proto_init() }
func file_chat_game_v1_client_proto_init() {
	if File_chat_game_v1_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_game_v1_client_proto_rawDesc), len(file_chat_game_v1_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_game_v1_client_proto_goTypes,
		DependencyIndexes: file_chat_game_v1_client_proto_depIdxs,
		MessageInfos:      file_chat_game_v1_client_proto_msgTypes,
	}.Build()
	File_chat_game_v1_client_proto = out.File
	file_chat_game_v1_client_proto_goTypes = nil
	file_chat_game_v1_client_proto_depIdxs = nil
}
