// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/server/v1/event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version *string                `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*ServerEvent_Error
	//	*ServerEvent_Rooms
	//	*ServerEvent_RoomJoined
	//	*ServerEvent_RoomLeft
	//	*ServerEvent_RoomUserJoined
	//	*ServerEvent_RoomUserLeft
	//	*ServerEvent_RoomGameStarted
	//	*ServerEvent_RoomGameStopped
	//	*ServerEvent_ServerTick
	Data          isServerEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_chat_server_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ServerEvent) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ServerEvent) GetData() isServerEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerEvent) GetError() *ServerError {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerEvent) GetRooms() *RoomInfos {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_Rooms); ok {
			return x.Rooms
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomJoined() *RoomJoined {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_RoomJoined); ok {
			return x.RoomJoined
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomLeft() *RoomLeft {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_RoomLeft); ok {
			return x.RoomLeft
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomUserJoined() *RoomUserJoined {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_RoomUserJoined); ok {
			return x.RoomUserJoined
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomUserLeft() *RoomUserLeft {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_RoomUserLeft); ok {
			return x.RoomUserLeft
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomGameStarted() *RoomGameStarted {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_RoomGameStarted); ok {
			return x.RoomGameStarted
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomGameStopped() *RoomGameStopped {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_RoomGameStopped); ok {
			return x.RoomGameStopped
		}
	}
	return nil
}

func (x *ServerEvent) GetServerTick() *ServerTick {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_ServerTick); ok {
			return x.ServerTick
		}
	}
	return nil
}

type isServerEvent_Data interface {
	isServerEvent_Data()
}

type ServerEvent_Error struct {
	Error *ServerError `protobuf:"bytes,2,opt,name=error,oneof"`
}

type ServerEvent_Rooms struct {
	Rooms *RoomInfos `protobuf:"bytes,3,opt,name=rooms,oneof"`
}

type ServerEvent_RoomJoined struct {
	RoomJoined *RoomJoined `protobuf:"bytes,4,opt,name=room_joined,json=roomJoined,oneof"`
}

type ServerEvent_RoomLeft struct {
	RoomLeft *RoomLeft `protobuf:"bytes,5,opt,name=room_left,json=roomLeft,oneof"`
}

type ServerEvent_RoomUserJoined struct {
	RoomUserJoined *RoomUserJoined `protobuf:"bytes,6,opt,name=room_user_joined,json=roomUserJoined,oneof"`
}

type ServerEvent_RoomUserLeft struct {
	RoomUserLeft *RoomUserLeft `protobuf:"bytes,7,opt,name=room_user_left,json=roomUserLeft,oneof"`
}

type ServerEvent_RoomGameStarted struct {
	RoomGameStarted *RoomGameStarted `protobuf:"bytes,8,opt,name=room_game_started,json=roomGameStarted,oneof"`
}

type ServerEvent_RoomGameStopped struct {
	RoomGameStopped *RoomGameStopped `protobuf:"bytes,9,opt,name=room_game_stopped,json=roomGameStopped,oneof"`
}

type ServerEvent_ServerTick struct {
	ServerTick *ServerTick `protobuf:"bytes,10,opt,name=server_tick,json=serverTick,oneof"`
}

func (*ServerEvent_Error) isServerEvent_Data() {}

func (*ServerEvent_Rooms) isServerEvent_Data() {}

func (*ServerEvent_RoomJoined) isServerEvent_Data() {}

func (*ServerEvent_RoomLeft) isServerEvent_Data() {}

func (*ServerEvent_RoomUserJoined) isServerEvent_Data() {}

func (*ServerEvent_RoomUserLeft) isServerEvent_Data() {}

func (*ServerEvent_RoomGameStarted) isServerEvent_Data() {}

func (*ServerEvent_RoomGameStopped) isServerEvent_Data() {}

func (*ServerEvent_ServerTick) isServerEvent_Data() {}

var File_chat_server_v1_event_proto protoreflect.FileDescriptor

const file_chat_server_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1achat/server/v1/event.proto\x12\x0echat.server.v1\x1a\x19chat/game/v1/server.proto\x1a!chat/server/v1/error_events.proto\x1a chat/server/v1/room_events.proto\x1a chat/server/v1/user_events.proto\"\xfc\x04\n" +
	"\vServerEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x123\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.chat.server.v1.ServerErrorH\x00R\x05error\x121\n" +
	"\x05rooms\x18\x03 \x01(\v2\x19.chat.server.v1.RoomInfosH\x00R\x05rooms\x12=\n" +
	"\vroom_joined\x18\x04 \x01(\v2\x1a.chat.server.v1.RoomJoinedH\x00R\n" +
	"roomJoined\x127\n" +
	"\troom_left\x18\x05 \x01(\v2\x18.chat.server.v1.RoomLeftH\x00R\broomLeft\x12J\n" +
	"\x10room_user_joined\x18\x06 \x01(\v2\x1e.chat.server.v1.RoomUserJoinedH\x00R\x0eroomUserJoined\x12D\n" +
	"\x0eroom_user_left\x18\a \x01(\v2\x1c.chat.server.v1.RoomUserLeftH\x00R\froomUserLeft\x12M\n" +
	"\x11room_game_started\x18\b \x01(\v2\x1f.chat.server.v1.RoomGameStartedH\x00R\x0froomGameStarted\x12M\n" +
	"\x11room_game_stopped\x18\t \x01(\v2\x1f.chat.server.v1.RoomGameStoppedH\x00R\x0froomGameStopped\x12;\n" +
	"\vserver_tick\x18\n" +
	" \x01(\v2\x18.chat.game.v1.ServerTickH\x00R\n" +
	"serverTickB\x06\n" +
	"\x04dataB\x83\x01\n" +
	"\x12com.chat.server.v1B\n" +
	"EventProtoP\x01Z\a./proto\xa2\x02\x03CSX\xaa\x02\x0eChat.Server.V1\xca\x02\x0eChat\\Server\\V1\xe2\x02\x1aChat\\Server\\V1\\GPBMetadata\xea\x02\x10Chat::Server::V1b\beditionsp\xe8\a"

var (
	file_chat_server_v1_event_proto_rawDescOnce sync.Once
	file_chat_server_v1_event_proto_rawDescData []byte
)

func file_chat_server_v1_event_proto_rawDescGZIP() []byte {
	file_chat_server_v1_event_proto_rawDescOnce.Do(func() {
		file_chat_server_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_server_v1_event_proto_rawDesc), len(file_chat_server_v1_event_proto_rawDesc)))
	})
	return file_chat_server_v1_event_proto_rawDescData
}

var file_chat_server_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_server_v1_event_proto_goTypes = []any{
	(*ServerEvent)(nil),     // 0: chat.server.v1.ServerEvent
	(*ServerError)(nil),     // 1: chat.server.v1.ServerError
	(*RoomInfos)(nil),       // 2: chat.server.v1.RoomInfos
	(*RoomJoined)(nil),      // 3: chat.server.v1.RoomJoined
	(*RoomLeft)(nil),        // 4: chat.server.v1.RoomLeft
	(*RoomUserJoined)(nil),  // 5: chat.server.v1.RoomUserJoined
	(*RoomUserLeft)(nil),    // 6: chat.server.v1.RoomUserLeft
	(*RoomGameStarted)(nil), // 7: chat.server.v1.RoomGameStarted
	(*RoomGameStopped)(nil), // 8: chat.server.v1.RoomGameStopped
	(*ServerTick)(nil),      // 9: chat.game.v1.ServerTick
}
var file_chat_server_v1_event_proto_depIdxs = []int32{
	1, // 0: chat.server.v1.ServerEvent.error:type_name -> chat.server.v1.ServerError
	2, // 1: chat.server.v1.ServerEvent.rooms:type_name -> chat.server.v1.RoomInfos
	3, // 2: chat.server.v1.ServerEvent.room_joined:type_name -> chat.server.v1.RoomJoined
	4, // 3: chat.server.v1.ServerEvent.room_left:type_name -> chat.server.v1.RoomLeft
	5, // 4: chat.server.v1.ServerEvent.room_user_joined:type_name -> chat.server.v1.RoomUserJoined
	6, // 5: chat.server.v1.ServerEvent.room_user_left:type_name -> chat.server.v1.RoomUserLeft
	7, // 6: chat.server.v1.ServerEvent.room_game_started:type_name -> chat.server.v1.RoomGameStarted
	8, // 7: chat.server.v1.ServerEvent.room_game_stopped:type_name -> chat.server.v1.RoomGameStopped
	9, // 8: chat.server.v1.ServerEvent.server_tick:type_name -> chat.game.v1.ServerTick
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_chat_server_v1_event_proto_init() }
func file_chat_server_v1_event_proto_init() {
	if File_chat_server_v1_event_proto != nil {
		return
	}
	file_chat_game_v1_server_proto_init()
	file_chat_server_v1_error_events_proto_init()
	file_chat_server_v1_room_events_proto_init()
	file_chat_server_v1_user_events_proto_init()
	file_chat_server_v1_event_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerEvent_Error)(nil),
		(*ServerEvent_Rooms)(nil),
		(*ServerEvent_RoomJoined)(nil),
		(*ServerEvent_RoomLeft)(nil),
		(*ServerEvent_RoomUserJoined)(nil),
		(*ServerEvent_RoomUserLeft)(nil),
		(*ServerEvent_RoomGameStarted)(nil),
		(*ServerEvent_RoomGameStopped)(nil),
		(*ServerEvent_ServerTick)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_server_v1_event_proto_rawDesc), len(file_chat_server_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_server_v1_event_proto_goTypes,
		DependencyIndexes: file_chat_server_v1_event_proto_depIdxs,
		MessageInfos:      file_chat_server_v1_event_proto_msgTypes,
	}.Build()
	File_chat_server_v1_event_proto = out.File
	file_chat_server_v1_event_proto_goTypes = nil
	file_chat_server_v1_event_proto_depIdxs = nil
}
