// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/server/v1/event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version *string                `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*ServerEvent_Rooms
	//	*ServerEvent_RoomJoined
	//	*ServerEvent_RoomLeft
	Data          isServerEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_chat_server_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ServerEvent) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ServerEvent) GetData() isServerEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerEvent) GetRooms() *RoomInfos {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_Rooms); ok {
			return x.Rooms
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomJoined() *RoomJoined {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_RoomJoined); ok {
			return x.RoomJoined
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomLeft() *RoomLeft {
	if x != nil {
		if x, ok := x.Data.(*ServerEvent_RoomLeft); ok {
			return x.RoomLeft
		}
	}
	return nil
}

type isServerEvent_Data interface {
	isServerEvent_Data()
}

type ServerEvent_Rooms struct {
	Rooms *RoomInfos `protobuf:"bytes,2,opt,name=rooms,oneof"`
}

type ServerEvent_RoomJoined struct {
	RoomJoined *RoomJoined `protobuf:"bytes,3,opt,name=room_joined,json=roomJoined,oneof"`
}

type ServerEvent_RoomLeft struct {
	RoomLeft *RoomLeft `protobuf:"bytes,4,opt,name=room_left,json=roomLeft,oneof"`
}

func (*ServerEvent_Rooms) isServerEvent_Data() {}

func (*ServerEvent_RoomJoined) isServerEvent_Data() {}

func (*ServerEvent_RoomLeft) isServerEvent_Data() {}

var File_chat_server_v1_event_proto protoreflect.FileDescriptor

const file_chat_server_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1achat/server/v1/event.proto\x12\x0echat.server.v1\x1a chat/server/v1/room_events.proto\"\xda\x01\n" +
	"\vServerEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x121\n" +
	"\x05rooms\x18\x02 \x01(\v2\x19.chat.server.v1.RoomInfosH\x00R\x05rooms\x12=\n" +
	"\vroom_joined\x18\x03 \x01(\v2\x1a.chat.server.v1.RoomJoinedH\x00R\n" +
	"roomJoined\x127\n" +
	"\troom_left\x18\x04 \x01(\v2\x18.chat.server.v1.RoomLeftH\x00R\broomLeftB\x06\n" +
	"\x04dataB\x83\x01\n" +
	"\x12com.chat.server.v1B\n" +
	"EventProtoP\x01Z\a./proto\xa2\x02\x03CSX\xaa\x02\x0eChat.Server.V1\xca\x02\x0eChat\\Server\\V1\xe2\x02\x1aChat\\Server\\V1\\GPBMetadata\xea\x02\x10Chat::Server::V1b\beditionsp\xe8\a"

var (
	file_chat_server_v1_event_proto_rawDescOnce sync.Once
	file_chat_server_v1_event_proto_rawDescData []byte
)

func file_chat_server_v1_event_proto_rawDescGZIP() []byte {
	file_chat_server_v1_event_proto_rawDescOnce.Do(func() {
		file_chat_server_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_server_v1_event_proto_rawDesc), len(file_chat_server_v1_event_proto_rawDesc)))
	})
	return file_chat_server_v1_event_proto_rawDescData
}

var file_chat_server_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_server_v1_event_proto_goTypes = []any{
	(*ServerEvent)(nil), // 0: chat.server.v1.ServerEvent
	(*RoomInfos)(nil),   // 1: chat.server.v1.RoomInfos
	(*RoomJoined)(nil),  // 2: chat.server.v1.RoomJoined
	(*RoomLeft)(nil),    // 3: chat.server.v1.RoomLeft
}
var file_chat_server_v1_event_proto_depIdxs = []int32{
	1, // 0: chat.server.v1.ServerEvent.rooms:type_name -> chat.server.v1.RoomInfos
	2, // 1: chat.server.v1.ServerEvent.room_joined:type_name -> chat.server.v1.RoomJoined
	3, // 2: chat.server.v1.ServerEvent.room_left:type_name -> chat.server.v1.RoomLeft
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chat_server_v1_event_proto_init() }
func file_chat_server_v1_event_proto_init() {
	if File_chat_server_v1_event_proto != nil {
		return
	}
	file_chat_server_v1_room_events_proto_init()
	file_chat_server_v1_event_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerEvent_Rooms)(nil),
		(*ServerEvent_RoomJoined)(nil),
		(*ServerEvent_RoomLeft)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_server_v1_event_proto_rawDesc), len(file_chat_server_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_server_v1_event_proto_goTypes,
		DependencyIndexes: file_chat_server_v1_event_proto_depIdxs,
		MessageInfos:      file_chat_server_v1_event_proto_msgTypes,
	}.Build()
	File_chat_server_v1_event_proto = out.File
	file_chat_server_v1_event_proto_goTypes = nil
	file_chat_server_v1_event_proto_depIdxs = nil
}
