// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/client/v1/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientGameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ClientGameRequest_Move
	//	*ClientGameRequest_Chat
	Data          isClientGameRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGameRequest) Reset() {
	*x = ClientGameRequest{}
	mi := &file_chat_client_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGameRequest) ProtoMessage() {}

func (x *ClientGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_client_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGameRequest.ProtoReflect.Descriptor instead.
func (*ClientGameRequest) Descriptor() ([]byte, []int) {
	return file_chat_client_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *ClientGameRequest) GetData() isClientGameRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientGameRequest) GetMove() *Move {
	if x != nil {
		if x, ok := x.Data.(*ClientGameRequest_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *ClientGameRequest) GetChat() *Chat {
	if x != nil {
		if x, ok := x.Data.(*ClientGameRequest_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

type isClientGameRequest_Data interface {
	isClientGameRequest_Data()
}

type ClientGameRequest_Move struct {
	Move *Move `protobuf:"bytes,1,opt,name=move,oneof"`
}

type ClientGameRequest_Chat struct {
	Chat *Chat `protobuf:"bytes,2,opt,name=chat,oneof"`
}

func (*ClientGameRequest_Move) isClientGameRequest_Data() {}

func (*ClientGameRequest_Chat) isClientGameRequest_Data() {}

var File_chat_client_v1_game_proto protoreflect.FileDescriptor

const file_chat_client_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x19chat/client/v1/game.proto\x12\x0echat.client.v1\x1a\x19chat/game/v1/client.proto\"o\n" +
	"\x11ClientGameRequest\x12(\n" +
	"\x04move\x18\x01 \x01(\v2\x12.chat.game.v1.MoveH\x00R\x04move\x12(\n" +
	"\x04chat\x18\x02 \x01(\v2\x12.chat.game.v1.ChatH\x00R\x04chatB\x06\n" +
	"\x04dataB\x82\x01\n" +
	"\x12com.chat.client.v1B\tGameProtoP\x01Z\a./proto\xa2\x02\x03CCX\xaa\x02\x0eChat.Client.V1\xca\x02\x0eChat\\Client\\V1\xe2\x02\x1aChat\\Client\\V1\\GPBMetadata\xea\x02\x10Chat::Client::V1b\beditionsp\xe8\a"

var (
	file_chat_client_v1_game_proto_rawDescOnce sync.Once
	file_chat_client_v1_game_proto_rawDescData []byte
)

func file_chat_client_v1_game_proto_rawDescGZIP() []byte {
	file_chat_client_v1_game_proto_rawDescOnce.Do(func() {
		file_chat_client_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_client_v1_game_proto_rawDesc), len(file_chat_client_v1_game_proto_rawDesc)))
	})
	return file_chat_client_v1_game_proto_rawDescData
}

var file_chat_client_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_client_v1_game_proto_goTypes = []any{
	(*ClientGameRequest)(nil), // 0: chat.client.v1.ClientGameRequest
	(*Move)(nil),              // 1: chat.game.v1.Move
	(*Chat)(nil),              // 2: chat.game.v1.Chat
}
var file_chat_client_v1_game_proto_depIdxs = []int32{
	1, // 0: chat.client.v1.ClientGameRequest.move:type_name -> chat.game.v1.Move
	2, // 1: chat.client.v1.ClientGameRequest.chat:type_name -> chat.game.v1.Chat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_client_v1_game_proto_init() }
func file_chat_client_v1_game_proto_init() {
	if File_chat_client_v1_game_proto != nil {
		return
	}
	file_chat_game_v1_client_proto_init()
	file_chat_client_v1_game_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientGameRequest_Move)(nil),
		(*ClientGameRequest_Chat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_client_v1_game_proto_rawDesc), len(file_chat_client_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_client_v1_game_proto_goTypes,
		DependencyIndexes: file_chat_client_v1_game_proto_depIdxs,
		MessageInfos:      file_chat_client_v1_game_proto_msgTypes,
	}.Build()
	File_chat_client_v1_game_proto = out.File
	file_chat_client_v1_game_proto_goTypes = nil
	file_chat_client_v1_game_proto_depIdxs = nil
}
