// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/client/v1/move.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float32               `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_chat_client_v1_move_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_chat_client_v1_move_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_chat_client_v1_move_proto_rawDescGZIP(), []int{0}
}

func (x *Move) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Move) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

var File_chat_client_v1_move_proto protoreflect.FileDescriptor

const file_chat_client_v1_move_proto_rawDesc = "" +
	"\n" +
	"\x19chat/client/v1/move.proto\x12\x0echat.client.v1\"\"\n" +
	"\x04Move\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01yB\x82\x01\n" +
	"\x12com.chat.client.v1B\tMoveProtoP\x01Z\a./proto\xa2\x02\x03CCX\xaa\x02\x0eChat.Client.V1\xca\x02\x0eChat\\Client\\V1\xe2\x02\x1aChat\\Client\\V1\\GPBMetadata\xea\x02\x10Chat::Client::V1b\beditionsp\xe8\a"

var (
	file_chat_client_v1_move_proto_rawDescOnce sync.Once
	file_chat_client_v1_move_proto_rawDescData []byte
)

func file_chat_client_v1_move_proto_rawDescGZIP() []byte {
	file_chat_client_v1_move_proto_rawDescOnce.Do(func() {
		file_chat_client_v1_move_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_client_v1_move_proto_rawDesc), len(file_chat_client_v1_move_proto_rawDesc)))
	})
	return file_chat_client_v1_move_proto_rawDescData
}

var file_chat_client_v1_move_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_client_v1_move_proto_goTypes = []any{
	(*Move)(nil), // 0: chat.client.v1.Move
}
var file_chat_client_v1_move_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_client_v1_move_proto_init() }
func file_chat_client_v1_move_proto_init() {
	if File_chat_client_v1_move_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_client_v1_move_proto_rawDesc), len(file_chat_client_v1_move_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_client_v1_move_proto_goTypes,
		DependencyIndexes: file_chat_client_v1_move_proto_depIdxs,
		MessageInfos:      file_chat_client_v1_move_proto_msgTypes,
	}.Build()
	File_chat_client_v1_move_proto = out.File
	file_chat_client_v1_move_proto_goTypes = nil
	file_chat_client_v1_move_proto_depIdxs = nil
}
