// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/client/v1/request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version *string                `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*ClientRequest_GetRooms
	//	*ClientRequest_JoinRoom
	//	*ClientRequest_LeaveRoom
	Data          isClientRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_chat_client_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_client_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_chat_client_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ClientRequest) GetData() isClientRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientRequest) GetGetRooms() *GetRooms {
	if x != nil {
		if x, ok := x.Data.(*ClientRequest_GetRooms); ok {
			return x.GetRooms
		}
	}
	return nil
}

func (x *ClientRequest) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.Data.(*ClientRequest_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *ClientRequest) GetLeaveRoom() *LeaveRoom {
	if x != nil {
		if x, ok := x.Data.(*ClientRequest_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

type isClientRequest_Data interface {
	isClientRequest_Data()
}

type ClientRequest_GetRooms struct {
	GetRooms *GetRooms `protobuf:"bytes,2,opt,name=get_rooms,json=getRooms,oneof"`
}

type ClientRequest_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,3,opt,name=join_room,json=joinRoom,oneof"`
}

type ClientRequest_LeaveRoom struct {
	LeaveRoom *LeaveRoom `protobuf:"bytes,4,opt,name=leave_room,json=leaveRoom,oneof"`
}

func (*ClientRequest_GetRooms) isClientRequest_Data() {}

func (*ClientRequest_JoinRoom) isClientRequest_Data() {}

func (*ClientRequest_LeaveRoom) isClientRequest_Data() {}

var File_chat_client_v1_request_proto protoreflect.FileDescriptor

const file_chat_client_v1_request_proto_rawDesc = "" +
	"\n" +
	"\x1cchat/client/v1/request.proto\x12\x0echat.client.v1\x1a\x19chat/client/v1/room.proto\"\xdf\x01\n" +
	"\rClientRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x127\n" +
	"\tget_rooms\x18\x02 \x01(\v2\x18.chat.client.v1.GetRoomsH\x00R\bgetRooms\x127\n" +
	"\tjoin_room\x18\x03 \x01(\v2\x18.chat.client.v1.JoinRoomH\x00R\bjoinRoom\x12:\n" +
	"\n" +
	"leave_room\x18\x04 \x01(\v2\x19.chat.client.v1.LeaveRoomH\x00R\tleaveRoomB\x06\n" +
	"\x04dataB\x85\x01\n" +
	"\x12com.chat.client.v1B\fRequestProtoP\x01Z\a./proto\xa2\x02\x03CCX\xaa\x02\x0eChat.Client.V1\xca\x02\x0eChat\\Client\\V1\xe2\x02\x1aChat\\Client\\V1\\GPBMetadata\xea\x02\x10Chat::Client::V1b\beditionsp\xe8\a"

var (
	file_chat_client_v1_request_proto_rawDescOnce sync.Once
	file_chat_client_v1_request_proto_rawDescData []byte
)

func file_chat_client_v1_request_proto_rawDescGZIP() []byte {
	file_chat_client_v1_request_proto_rawDescOnce.Do(func() {
		file_chat_client_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_client_v1_request_proto_rawDesc), len(file_chat_client_v1_request_proto_rawDesc)))
	})
	return file_chat_client_v1_request_proto_rawDescData
}

var file_chat_client_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_client_v1_request_proto_goTypes = []any{
	(*ClientRequest)(nil), // 0: chat.client.v1.ClientRequest
	(*GetRooms)(nil),      // 1: chat.client.v1.GetRooms
	(*JoinRoom)(nil),      // 2: chat.client.v1.JoinRoom
	(*LeaveRoom)(nil),     // 3: chat.client.v1.LeaveRoom
}
var file_chat_client_v1_request_proto_depIdxs = []int32{
	1, // 0: chat.client.v1.ClientRequest.get_rooms:type_name -> chat.client.v1.GetRooms
	2, // 1: chat.client.v1.ClientRequest.join_room:type_name -> chat.client.v1.JoinRoom
	3, // 2: chat.client.v1.ClientRequest.leave_room:type_name -> chat.client.v1.LeaveRoom
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chat_client_v1_request_proto_init() }
func file_chat_client_v1_request_proto_init() {
	if File_chat_client_v1_request_proto != nil {
		return
	}
	file_chat_client_v1_room_proto_init()
	file_chat_client_v1_request_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientRequest_GetRooms)(nil),
		(*ClientRequest_JoinRoom)(nil),
		(*ClientRequest_LeaveRoom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_client_v1_request_proto_rawDesc), len(file_chat_client_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_client_v1_request_proto_goTypes,
		DependencyIndexes: file_chat_client_v1_request_proto_depIdxs,
		MessageInfos:      file_chat_client_v1_request_proto_msgTypes,
	}.Build()
	File_chat_client_v1_request_proto = out.File
	file_chat_client_v1_request_proto_goTypes = nil
	file_chat_client_v1_request_proto_depIdxs = nil
}
