// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/server/v1/room_events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           *int64                 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_chat_server_v1_room_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_room_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_room_events_proto_rawDescGZIP(), []int{0}
}

func (x *RoomInfo) GetNum() int64 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

func (x *RoomInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type RoomInfos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfos) Reset() {
	*x = RoomInfos{}
	mi := &file_chat_server_v1_room_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfos) ProtoMessage() {}

func (x *RoomInfos) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_room_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfos.ProtoReflect.Descriptor instead.
func (*RoomInfos) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_room_events_proto_rawDescGZIP(), []int{1}
}

func (x *RoomInfos) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type RoomJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           *int64                 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner         *ServerUserInfo        `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	Users         []*ServerUserInfo      `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoined) Reset() {
	*x = RoomJoined{}
	mi := &file_chat_server_v1_room_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoined) ProtoMessage() {}

func (x *RoomJoined) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_room_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoined.ProtoReflect.Descriptor instead.
func (*RoomJoined) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_room_events_proto_rawDescGZIP(), []int{2}
}

func (x *RoomJoined) GetNum() int64 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

func (x *RoomJoined) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RoomJoined) GetOwner() *ServerUserInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *RoomJoined) GetUsers() []*ServerUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type RoomLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeft) Reset() {
	*x = RoomLeft{}
	mi := &file_chat_server_v1_room_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeft) ProtoMessage() {}

func (x *RoomLeft) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_room_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeft.ProtoReflect.Descriptor instead.
func (*RoomLeft) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_room_events_proto_rawDescGZIP(), []int{3}
}

type RoomUserJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ServerUserInfo        `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomUserJoined) Reset() {
	*x = RoomUserJoined{}
	mi := &file_chat_server_v1_room_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomUserJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUserJoined) ProtoMessage() {}

func (x *RoomUserJoined) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_room_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUserJoined.ProtoReflect.Descriptor instead.
func (*RoomUserJoined) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_room_events_proto_rawDescGZIP(), []int{4}
}

func (x *RoomUserJoined) GetUser() *ServerUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type RoomUserLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ServerUserInfo        `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomUserLeft) Reset() {
	*x = RoomUserLeft{}
	mi := &file_chat_server_v1_room_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomUserLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUserLeft) ProtoMessage() {}

func (x *RoomUserLeft) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_room_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUserLeft.ProtoReflect.Descriptor instead.
func (*RoomUserLeft) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_room_events_proto_rawDescGZIP(), []int{5}
}

func (x *RoomUserLeft) GetUser() *ServerUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

var File_chat_server_v1_room_events_proto protoreflect.FileDescriptor

const file_chat_server_v1_room_events_proto_rawDesc = "" +
	"\n" +
	" chat/server/v1/room_events.proto\x12\x0echat.server.v1\x1a chat/server/v1/server_user.proto\"0\n" +
	"\bRoomInfo\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\tRoomInfos\x12.\n" +
	"\x05rooms\x18\x01 \x03(\v2\x18.chat.server.v1.RoomInfoR\x05rooms\"\x9e\x01\n" +
	"\n" +
	"RoomJoined\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\x05owner\x18\x03 \x01(\v2\x1e.chat.server.v1.ServerUserInfoR\x05owner\x124\n" +
	"\x05users\x18\x04 \x03(\v2\x1e.chat.server.v1.ServerUserInfoR\x05users\"\n" +
	"\n" +
	"\bRoomLeft\"D\n" +
	"\x0eRoomUserJoined\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.chat.server.v1.ServerUserInfoR\x04user\"B\n" +
	"\fRoomUserLeft\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.chat.server.v1.ServerUserInfoR\x04userB\x88\x01\n" +
	"\x12com.chat.server.v1B\x0fRoomEventsProtoP\x01Z\a./proto\xa2\x02\x03CSX\xaa\x02\x0eChat.Server.V1\xca\x02\x0eChat\\Server\\V1\xe2\x02\x1aChat\\Server\\V1\\GPBMetadata\xea\x02\x10Chat::Server::V1b\beditionsp\xe8\a"

var (
	file_chat_server_v1_room_events_proto_rawDescOnce sync.Once
	file_chat_server_v1_room_events_proto_rawDescData []byte
)

func file_chat_server_v1_room_events_proto_rawDescGZIP() []byte {
	file_chat_server_v1_room_events_proto_rawDescOnce.Do(func() {
		file_chat_server_v1_room_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_server_v1_room_events_proto_rawDesc), len(file_chat_server_v1_room_events_proto_rawDesc)))
	})
	return file_chat_server_v1_room_events_proto_rawDescData
}

var file_chat_server_v1_room_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chat_server_v1_room_events_proto_goTypes = []any{
	(*RoomInfo)(nil),       // 0: chat.server.v1.RoomInfo
	(*RoomInfos)(nil),      // 1: chat.server.v1.RoomInfos
	(*RoomJoined)(nil),     // 2: chat.server.v1.RoomJoined
	(*RoomLeft)(nil),       // 3: chat.server.v1.RoomLeft
	(*RoomUserJoined)(nil), // 4: chat.server.v1.RoomUserJoined
	(*RoomUserLeft)(nil),   // 5: chat.server.v1.RoomUserLeft
	(*ServerUserInfo)(nil), // 6: chat.server.v1.ServerUserInfo
}
var file_chat_server_v1_room_events_proto_depIdxs = []int32{
	0, // 0: chat.server.v1.RoomInfos.rooms:type_name -> chat.server.v1.RoomInfo
	6, // 1: chat.server.v1.RoomJoined.owner:type_name -> chat.server.v1.ServerUserInfo
	6, // 2: chat.server.v1.RoomJoined.users:type_name -> chat.server.v1.ServerUserInfo
	6, // 3: chat.server.v1.RoomUserJoined.user:type_name -> chat.server.v1.ServerUserInfo
	6, // 4: chat.server.v1.RoomUserLeft.user:type_name -> chat.server.v1.ServerUserInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_chat_server_v1_room_events_proto_init() }
func file_chat_server_v1_room_events_proto_init() {
	if File_chat_server_v1_room_events_proto != nil {
		return
	}
	file_chat_server_v1_server_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_server_v1_room_events_proto_rawDesc), len(file_chat_server_v1_room_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_server_v1_room_events_proto_goTypes,
		DependencyIndexes: file_chat_server_v1_room_events_proto_depIdxs,
		MessageInfos:      file_chat_server_v1_room_events_proto_msgTypes,
	}.Build()
	File_chat_server_v1_room_events_proto = out.File
	file_chat_server_v1_room_events_proto_goTypes = nil
	file_chat_server_v1_room_events_proto_depIdxs = nil
}
