// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/client/v1/room.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRooms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRooms) Reset() {
	*x = GetRooms{}
	mi := &file_chat_client_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRooms) ProtoMessage() {}

func (x *GetRooms) ProtoReflect() protoreflect.Message {
	mi := &file_chat_client_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRooms.ProtoReflect.Descriptor instead.
func (*GetRooms) Descriptor() ([]byte, []int) {
	return file_chat_client_v1_room_proto_rawDescGZIP(), []int{0}
}

type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           *int64                 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_chat_client_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_chat_client_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_chat_client_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRoom) GetNum() int64 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

type LeaveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoom) Reset() {
	*x = LeaveRoom{}
	mi := &file_chat_client_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom) ProtoMessage() {}

func (x *LeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_chat_client_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom.ProtoReflect.Descriptor instead.
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return file_chat_client_v1_room_proto_rawDescGZIP(), []int{2}
}

type RoomStartGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStartGame) Reset() {
	*x = RoomStartGame{}
	mi := &file_chat_client_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStartGame) ProtoMessage() {}

func (x *RoomStartGame) ProtoReflect() protoreflect.Message {
	mi := &file_chat_client_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStartGame.ProtoReflect.Descriptor instead.
func (*RoomStartGame) Descriptor() ([]byte, []int) {
	return file_chat_client_v1_room_proto_rawDescGZIP(), []int{3}
}

type RoomStopGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStopGame) Reset() {
	*x = RoomStopGame{}
	mi := &file_chat_client_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStopGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStopGame) ProtoMessage() {}

func (x *RoomStopGame) ProtoReflect() protoreflect.Message {
	mi := &file_chat_client_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStopGame.ProtoReflect.Descriptor instead.
func (*RoomStopGame) Descriptor() ([]byte, []int) {
	return file_chat_client_v1_room_proto_rawDescGZIP(), []int{4}
}

var File_chat_client_v1_room_proto protoreflect.FileDescriptor

const file_chat_client_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x19chat/client/v1/room.proto\x12\x0echat.client.v1\"\n" +
	"\n" +
	"\bGetRooms\"\x1c\n" +
	"\bJoinRoom\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num\"\v\n" +
	"\tLeaveRoom\"\x0f\n" +
	"\rRoomStartGame\"\x0e\n" +
	"\fRoomStopGameB\x82\x01\n" +
	"\x12com.chat.client.v1B\tRoomProtoP\x01Z\a./proto\xa2\x02\x03CCX\xaa\x02\x0eChat.Client.V1\xca\x02\x0eChat\\Client\\V1\xe2\x02\x1aChat\\Client\\V1\\GPBMetadata\xea\x02\x10Chat::Client::V1b\beditionsp\xe8\a"

var (
	file_chat_client_v1_room_proto_rawDescOnce sync.Once
	file_chat_client_v1_room_proto_rawDescData []byte
)

func file_chat_client_v1_room_proto_rawDescGZIP() []byte {
	file_chat_client_v1_room_proto_rawDescOnce.Do(func() {
		file_chat_client_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_client_v1_room_proto_rawDesc), len(file_chat_client_v1_room_proto_rawDesc)))
	})
	return file_chat_client_v1_room_proto_rawDescData
}

var file_chat_client_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chat_client_v1_room_proto_goTypes = []any{
	(*GetRooms)(nil),      // 0: chat.client.v1.GetRooms
	(*JoinRoom)(nil),      // 1: chat.client.v1.JoinRoom
	(*LeaveRoom)(nil),     // 2: chat.client.v1.LeaveRoom
	(*RoomStartGame)(nil), // 3: chat.client.v1.RoomStartGame
	(*RoomStopGame)(nil),  // 4: chat.client.v1.RoomStopGame
}
var file_chat_client_v1_room_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_client_v1_room_proto_init() }
func file_chat_client_v1_room_proto_init() {
	if File_chat_client_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_client_v1_room_proto_rawDesc), len(file_chat_client_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_client_v1_room_proto_goTypes,
		DependencyIndexes: file_chat_client_v1_room_proto_depIdxs,
		MessageInfos:      file_chat_client_v1_room_proto_msgTypes,
	}.Build()
	File_chat_client_v1_room_proto = out.File
	file_chat_client_v1_room_proto_goTypes = nil
	file_chat_client_v1_room_proto_depIdxs = nil
}
