// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/game/v1/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	X             *float64               `protobuf:"fixed64,3,opt,name=x" json:"x,omitempty"`
	Y             *float64               `protobuf:"fixed64,4,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_chat_game_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_chat_game_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_chat_game_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *PlayerState) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PlayerState) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *PlayerState) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      *string                `protobuf:"bytes,1,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_game_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_game_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_game_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type ServerTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerState         `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTick) Reset() {
	*x = ServerTick{}
	mi := &file_chat_game_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTick) ProtoMessage() {}

func (x *ServerTick) ProtoReflect() protoreflect.Message {
	mi := &file_chat_game_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTick.ProtoReflect.Descriptor instead.
func (*ServerTick) Descriptor() ([]byte, []int) {
	return file_chat_game_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *ServerTick) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *ServerTick) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_chat_game_v1_server_proto protoreflect.FileDescriptor

const file_chat_game_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x19chat/game/v1/server.proto\x12\fchat.game.v1\"M\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x01R\x01y\"D\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\n" +
	"ServerTick\x123\n" +
	"\aplayers\x18\x01 \x03(\v2\x19.chat.game.v1.PlayerStateR\aplayers\x125\n" +
	"\bmessages\x18\x02 \x03(\v2\x19.chat.game.v1.ChatMessageR\bmessagesBz\n" +
	"\x10com.chat.game.v1B\vServerProtoP\x01Z\a./proto\xa2\x02\x03CGX\xaa\x02\fChat.Game.V1\xca\x02\fChat\\Game\\V1\xe2\x02\x18Chat\\Game\\V1\\GPBMetadata\xea\x02\x0eChat::Game::V1b\beditionsp\xe8\a"

var (
	file_chat_game_v1_server_proto_rawDescOnce sync.Once
	file_chat_game_v1_server_proto_rawDescData []byte
)

func file_chat_game_v1_server_proto_rawDescGZIP() []byte {
	file_chat_game_v1_server_proto_rawDescOnce.Do(func() {
		file_chat_game_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_game_v1_server_proto_rawDesc), len(file_chat_game_v1_server_proto_rawDesc)))
	})
	return file_chat_game_v1_server_proto_rawDescData
}

var file_chat_game_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chat_game_v1_server_proto_goTypes = []any{
	(*PlayerState)(nil), // 0: chat.game.v1.PlayerState
	(*ChatMessage)(nil), // 1: chat.game.v1.ChatMessage
	(*ServerTick)(nil),  // 2: chat.game.v1.ServerTick
}
var file_chat_game_v1_server_proto_depIdxs = []int32{
	0, // 0: chat.game.v1.ServerTick.players:type_name -> chat.game.v1.PlayerState
	1, // 1: chat.game.v1.ServerTick.messages:type_name -> chat.game.v1.ChatMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_game_v1_server_proto_init() }
func file_chat_game_v1_server_proto_init() {
	if File_chat_game_v1_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_game_v1_server_proto_rawDesc), len(file_chat_game_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_game_v1_server_proto_goTypes,
		DependencyIndexes: file_chat_game_v1_server_proto_depIdxs,
		MessageInfos:      file_chat_game_v1_server_proto_msgTypes,
	}.Build()
	File_chat_game_v1_server_proto = out.File
	file_chat_game_v1_server_proto_goTypes = nil
	file_chat_game_v1_server_proto_depIdxs = nil
}
