// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/game/v1/state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *string                `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_chat_game_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_chat_game_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_chat_game_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *GameState) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

var File_chat_game_v1_state_proto protoreflect.FileDescriptor

const file_chat_game_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x18chat/game/v1/state.proto\x12\fchat.game.v1\"%\n" +
	"\tGameState\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversionBy\n" +
	"\x10com.chat.game.v1B\n" +
	"StateProtoP\x01Z\a./proto\xa2\x02\x03CGX\xaa\x02\fChat.Game.V1\xca\x02\fChat\\Game\\V1\xe2\x02\x18Chat\\Game\\V1\\GPBMetadata\xea\x02\x0eChat::Game::V1b\beditionsp\xe8\a"

var (
	file_chat_game_v1_state_proto_rawDescOnce sync.Once
	file_chat_game_v1_state_proto_rawDescData []byte
)

func file_chat_game_v1_state_proto_rawDescGZIP() []byte {
	file_chat_game_v1_state_proto_rawDescOnce.Do(func() {
		file_chat_game_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_game_v1_state_proto_rawDesc), len(file_chat_game_v1_state_proto_rawDesc)))
	})
	return file_chat_game_v1_state_proto_rawDescData
}

var file_chat_game_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_game_v1_state_proto_goTypes = []any{
	(*GameState)(nil), // 0: chat.game.v1.GameState
}
var file_chat_game_v1_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_game_v1_state_proto_init() }
func file_chat_game_v1_state_proto_init() {
	if File_chat_game_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_game_v1_state_proto_rawDesc), len(file_chat_game_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_game_v1_state_proto_goTypes,
		DependencyIndexes: file_chat_game_v1_state_proto_depIdxs,
		MessageInfos:      file_chat_game_v1_state_proto_msgTypes,
	}.Build()
	File_chat_game_v1_state_proto = out.File
	file_chat_game_v1_state_proto_goTypes = nil
	file_chat_game_v1_state_proto_depIdxs = nil
}
