// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/server/v1/user_events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUserInfo) Reset() {
	*x = ServerUserInfo{}
	mi := &file_chat_server_v1_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUserInfo) ProtoMessage() {}

func (x *ServerUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_v1_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUserInfo.ProtoReflect.Descriptor instead.
func (*ServerUserInfo) Descriptor() ([]byte, []int) {
	return file_chat_server_v1_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *ServerUserInfo) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ServerUserInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_chat_server_v1_user_events_proto protoreflect.FileDescriptor

const file_chat_server_v1_user_events_proto_rawDesc = "" +
	"\n" +
	" chat/server/v1/user_events.proto\x12\x0echat.server.v1\"4\n" +
	"\x0eServerUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\x88\x01\n" +
	"\x12com.chat.server.v1B\x0fUserEventsProtoP\x01Z\a./proto\xa2\x02\x03CSX\xaa\x02\x0eChat.Server.V1\xca\x02\x0eChat\\Server\\V1\xe2\x02\x1aChat\\Server\\V1\\GPBMetadata\xea\x02\x10Chat::Server::V1b\beditionsp\xe8\a"

var (
	file_chat_server_v1_user_events_proto_rawDescOnce sync.Once
	file_chat_server_v1_user_events_proto_rawDescData []byte
)

func file_chat_server_v1_user_events_proto_rawDescGZIP() []byte {
	file_chat_server_v1_user_events_proto_rawDescOnce.Do(func() {
		file_chat_server_v1_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_server_v1_user_events_proto_rawDesc), len(file_chat_server_v1_user_events_proto_rawDesc)))
	})
	return file_chat_server_v1_user_events_proto_rawDescData
}

var file_chat_server_v1_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_server_v1_user_events_proto_goTypes = []any{
	(*ServerUserInfo)(nil), // 0: chat.server.v1.ServerUserInfo
}
var file_chat_server_v1_user_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_server_v1_user_events_proto_init() }
func file_chat_server_v1_user_events_proto_init() {
	if File_chat_server_v1_user_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_server_v1_user_events_proto_rawDesc), len(file_chat_server_v1_user_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_server_v1_user_events_proto_goTypes,
		DependencyIndexes: file_chat_server_v1_user_events_proto_depIdxs,
		MessageInfos:      file_chat_server_v1_user_events_proto_msgTypes,
	}.Build()
	File_chat_server_v1_user_events_proto = out.File
	file_chat_server_v1_user_events_proto_goTypes = nil
	file_chat_server_v1_user_events_proto_depIdxs = nil
}
